spring:
  application:
    name: StudyCam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

koul:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000