spring:
  application:
    name: StudyCam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

koul:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000

livekit:
  api:
    key: ${LIVEKIT_KEY}
    secret: ${LIVEKIT_SECRET}
    url: ${LIVEKIT_URL}